parameters:
- name: listOfVars
  type: object
  default:
  - $(Build.BuildNumber)
  - $(Build.BuildId)
  - $(Build.Reason)

steps:
- ${{ each value in parameters.listOfVars }}:
  - script: echo ${{ value }}