# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

stages:

- stage: BUILD
  displayName: 'Package helm charts'
  pool:
    name: agentvmss
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: index.html
      TargetFolder: '$(build.artifactstagingdirectory)'


- stage: BUILD2
  displayName: 'Package helm charts'
  pool:
    name: agentvmss
  steps:
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
    inputs:
      SourceFolder: index.html
      TargetFolder: '$(build.artifactstagingdirectory)'
 

