# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: agentvmss

stages:

- stage: BUILD
  displayName: 'Package helm charts'
  pool:
    #vmImage: windows-2019
    name: agentvmss
  jobs:
  - job: BUILD
    displayName: 'Package helm charts'
    script:
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
      
- stage: BUILD2
  displayName: 'Package helm charts'
  pool:
    #vmImage: windows-2019
    name: agentvmss
  jobs:
  - job: BUILD
    displayName: 'Package helm charts'
    script:
      echo Add other tasks to build, test, and deploy your project.
      echo See https://aka.ms/yaml
 

