variables:
 - name: pullRequest
   value: 
   - $Build.Reason
   - $Build.BuildUri
   - $Build.BuildNumber
steps: 
- bash: echo $(pullRequest[Build.BuildNumber])
- powershell: echo $(pullRequest)
- script: echo $(pullRequest)