parameters:
- name: image
  displayName: Pool Image
  values:
  - $(Build.BuildNumber)

jobs:
- job: build
  displayName: build
  pool: 
    vmImage: ${{ parameters.image }}
  steps:
  - script: echo building with ${{ parameters.image }}