parameters:
- name: image
  displayName: Vars
  values:
  - $(Build.BuildNumber)
  - $(Build.Reason)
  - $(Build.BuildUri)

jobs:
- job: build
  displayName: buildnumber
  steps:
  - script: echo building with ${{ parameters.image }}
- job: build
  displayName: buildreason
  steps:
  - script: echo building with ${{ parameters.image }}
- job: build
  displayName: builduri
  steps:
  - script: echo building with ${{ parameters.image }}
